### ISSUE TITLE
Test and rethink `bito` acceleration

### ISSUE THREAD

**Issue by christiaanjs** [christiaanjs/treeflow#46]
* Vectorisation/parallelisation
* Run tests
* How to integrate with `tfp.Bijector/Distribution` framework?
Best to wait for [new `bito` build process](https://github.com/phylovi/bito/pull/381)?

**Comment by matsen** [comment]
We'd love for you to try out the build. That branch should be usable now, though you'll need to be hand-set-up your pythonpath to see it.

The next step is a pip-installable package, but that's a little ways out.
